### ISSUE TITLE
npm ERR! Exit status 132 | Illegal instruction: 4  xcodebuild

### ISSUE THREAD

**Issue by WuglyakBolgoink** [ios-control/ios-deploy#480]
# Expected behavior

install package in global scope

# Actual behavior.

Run:
```shell
sudo npm install -g ios-deploy --unsafe-perm=true -E --verbose
```

Got:
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/usr/local/Cellar/node/14.13.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'ios-deploy',
npm verb cli   '--unsafe-perm=true',
npm verb cli   '-E',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.8
npm info using node@v14.13.0
npm verb npm-session 10b14cb17381068d
npm http fetch GET 304 https://registry.npmjs.org/ios-deploy 161ms (from cache)
npm timing stage:loadCurrentTree Completed in 201ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4ms
npm timing stage:loadIdealTree Completed in 6ms
npm timing stage:generateActionsToTake Completed in 3ms
npm verb correctMkdir /Users/MY_USER_NAME/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/MY_USER_NAME/.npm/_locks/staging-6c4c9e8a6d8f0e2b.lock for /Users/MY_USER_NAME/.npm-global/lib/node_modules/.staging
npm timing action:extract Completed in 30ms
npm timing action:finalize Completed in 4ms
npm timing action:refresh-package-json Completed in 13ms
npm info lifecycle ios-deploy@1.11.2~preinstall: ios-deploy@1.11.2

> ios-deploy@1.11.2 preinstall /Users/MY_USER_NAME/.npm-global/lib/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

note: Using new build system
note: Planning build
note: Constructing build description
sh: line 1: 34970 Illegal instruction: 4  xcodebuild
npm verb lifecycle ios-deploy@1.11.2~preinstall: unsafe-perm in lifecycle true
npm verb lifecycle ios-deploy@1.11.2~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/MY_USER_NAME/.npm-global/lib/node_modules/ios-deploy/node_modules/.bin:/Users/MY_USER_NAME/.npm-global/lib/node_modules/.bin:/usr/local/opt/node@10/bin:/Users/MY_USER_NAME/dev/SDKs/phantomjs-2.1.1/bin:/bin:/usr/local/bin:/Users/MY_USER_NAME/bin:/Users/MY_USER_NAME/Library/Android/sdk/platform-tools:/Users/MY_USER_NAME/Library/Android/sdk/tools:/Users/MY_USER_NAME/Library/Android/sdk/tools/bin:/Users/MY_USER_NAME/Library/Android/sdk/build-tools/29.0.2:/Users/MY_USER_NAME/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/MY_USER_NAME/.composer/vendor/bin
npm verb lifecycle ios-deploy@1.11.2~preinstall: CWD: /Users/MY_USER_NAME/.npm-global/lib/node_modules/ios-deploy
npm info lifecycle ios-deploy@1.11.2~preinstall: Failed to exec preinstall script
npm timing action:preinstall Completed in 2756ms
npm verb unlock done using /Users/MY_USER_NAME/.npm/_locks/staging-6c4c9e8a6d8f0e2b.lock for /Users/MY_USER_NAME/.npm-global/lib/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 8ms
npm timing stage:runTopLevelLifecycles Completed in 3030ms
npm verb stack Error: ios-deploy@1.11.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm verb stack Exit status 132
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1047:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid ios-deploy@1.11.2
npm verb cwd /Users/MY_USER_NAME
npm verb Darwin 19.6.0
npm verb argv "/usr/local/Cellar/node/14.13.0/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy" "--unsafe-perm=true" "-E" "--verbose"
npm verb node v14.13.0
npm verb npm  v6.14.8
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! ios-deploy@1.11.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 132
npm ERR! 
npm ERR! Failed at the ios-deploy@1.11.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 132, true ]
npm timing npm Completed in 3323ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MY_USER_NAME/.npm/_logs/2020-10-06T14_45_33_837Z-debug.log
```

# Steps to reproduce the problem

see above

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType

```
Software:
    System Software Overview:
      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6:39
```

- [x] 2. ios-deploy -V

```
zsh: command not found: ios-deploy
```

- [x] 3. xcodebuild -version

```
Xcode 12.0.1
Build version 12A7300
```

- [x] 4. xcode-select --print-path

```
/Applications/Xcode.app/Contents/Developer
```

- [x] 5. gcc --version

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

- [x] 6. lldb --version

```
lldb-1200.0.32.1
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
```

- [x] **If using NodeJS/npm**
  - [x] 7. npm -v
```6.14.8```
  - [x] 8. node -v
```v14.13.0```

**Comment by WuglyakBolgoink** [comment]
maybe related to https://github.com/ios-control/ios-deploy/issues/465

**Comment by WuglyakBolgoink** [comment]
@gabebear actually, I installed this with brew successful.
the reason is, that macOS always need root permissions to install packages in global scope (`npm i -g <pkg>`)... If anyone know how I can skip this will be helpful!

**Comment by gabebear** [comment]
You can actually install globally with npm without using sudo... but once you've installed one package with npm using sudo it gets to be a giant mess and a lot of tutorials will tell you to use sudo. https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Comment by gabebear** [comment]
ha, I had forgotten about foolish-code.com... I'll go figure out what is wrong.
