### ISSUE TITLE
Cannot select xcode version when deploying

### ISSUE THREAD

**Issue by zhilinghuang** [ios-control/ios-deploy#522]
Include the **command line arguments** you used for ios-deploy.
ios-deploy --bundle --debug..

# Expected behavior
Should have a --xcode_path option to select xcode

# Actual behavior.
Randomly pick one xcode for no reason

# Steps to reproduce the problem
Just try deploy and run any app

# System Specs
Any system with multiple xcode

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
- [ ] 2. ios-deploy -V
- [ ] 3. xcodebuild -version
- [ ] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version
- [ ] **If using NodeJS/npm**
  - [ ] 7. npm -v
  - [ ] 8. node -v

**Comment by zhilinghuang** [comment]
Please help, anyone.

**Comment by gabebear** [comment]
ios-deploy should be using the version of Xcode set to be used with command line tools.

You can see what Xcode is used with
```
 xcode-select -p
```

You can set a specifc Xcode with something like
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by zhilinghuang** [comment]
Hi @gabebear , It exists. 

What you are talking about is the device support directory for a specific iOS version.

However what cause the problem of the "symbols" cannot be found is the lack of debugging support directory for the iOS version. The debugging symbols are usually located in "/Users/<user account>/Library/Developer/Xcode/iOS\ DeviceSupport/". Be aware that even it is DeviceSupport, it is a different DeviceSupport directory.

Is there anyway to programmatically generate these symbols?

**Comment by zhilinghuang** [comment]
@gabebear  I have updated the issue's description.

**Comment by ivanhernandez13** [comment]
Have you opened Xcode with the device plugged in? That directory is created by Xcode and Xcode will show something like "Preparing debugger support for iPhone 12" in the center top of the GUI where it shows all progress notifications.

**Comment by gabebear** [comment]
Each Xcode version comes with support for a specific set of iOS versions. Does your device work in the `Xcode12.5` GUI?

If you can hook the debugger to your device in  the `Xcode12.5` GUI then it is something wrong in ios-deploy.

**_NOT SOMETHING WE OFFER SUPPORT FOR,_**  but you can usually copy the "DeviceSupport" folders between different versions of Xcode to add support for different iOS versions. 
https://stackoverflow.com/questions/39655178/xcode-could-not-locate-device-support-files

**Comment by itsalfredakku** [comment]
I've been meshed up with this
```
[   +6 ms] Installing and launching...
[        ] Debugging is enabled, connecting to vmService
[   +7 ms] executing: script -t 0 /dev/null /Users/akash/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 00008101-00051D500110001E --bundle build/ios/iphoneos/Runner.app --app_deltas build/ios/app-delta --debug --no-wifi
--args --enable-dart-profiling --enable-checked-mode --verify-entry-points
[  +57 ms] [....] Waiting for iOS device to be connected
[ +202 ms] [....] Using 00008101-00051D500110001E (D53gAP, iPhone 12, iphoneos, arm64e, 17.0, 21A5277j) a.k.a. 'AKASH’s iPhone'.
[        ] ------ Install phase ------
[        ] [  0%] Found 00008101-00051D500110001E (D53gAP, iPhone 12, iphoneos, arm64e, 17.0, 21A5277j) a.k.a. 'AKASH’s iPhone' connected through USB, beginning install
[ +668 ms] [  5%] TransferringPackage
[        ] [  5%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/META-INF/ to device
[        ] [  5%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  6%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  6%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/ to device
[        ] [  7%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/ to device
[        ] [  7%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/ to device
[   +2 ms] [  8%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/ to device
[        ] [  8%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/_CodeSignature/ to device
[        ] [  9%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/_CodeSignature/ to device
[        ] [  9%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/_CodeSignature/CodeResources to device
[        ] [ 10%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/_CodeSignature/CodeResources to device
[        ] [ 10%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Info.plist to device
[        ] [ 10%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Runner to device
[  +18 ms] [ 11%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Runner to device
[        ] [ 11%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/com.apple.deltainstallcommands.com.devstroop.untitled to device
[        ] [ 12%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/com.apple.deltainstallcommands.com.devstroop.untitled to device
[        ] [ 12%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/ to device
[        ] [ 13%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/ to device
[        ] [ 13%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 14%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 14%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [ 15%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [ 15%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[        ] [ 15%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[  +22 ms] [ 16%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +225 ms] [ 17%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +265 ms] [ 18%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +235 ms] [ 19%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +238 ms] [ 20%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +201 ms] [ 21%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +189 ms] [ 22%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +190 ms] [ 23%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +178 ms] [ 24%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +193 ms] [ 25%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +179 ms] [ 26%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +176 ms] [ 27%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +194 ms] [ 28%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/Flutter.framework/Flutter to device
[  +10 ms] [ 28%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/ to device
[        ] [ 29%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/ to device
[        ] [ 29%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 30%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 30%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[        ] [ 31%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[        ] [ 31%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/App to device
[        ] [ 32%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/App to device
[        ] [ 32%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 33%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 33%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z to device
[   +1 ms] [ 33%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[        ] [ 34%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[        ] [ 34%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[  +67 ms] [ 35%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +265 ms] [ 36%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +261 ms] [ 37%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +253 ms] [ 38%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +248 ms] [ 39%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +186 ms] [ 40%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +189 ms] [ 41%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +177 ms] [ 42%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +186 ms] [ 43%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +188 ms] [ 44%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +178 ms] [ 45%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[        ] [ 45%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[        ] [ 46%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[        ] [ 46%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/shaders/ to device
[        ] [ 47%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/shaders/ to device
[        ] [ 47%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/shaders/ink_sparkle.frag to device
[        ] [ 48%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/shaders/ink_sparkle.frag to device
[        ] [ 48%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.bin to device
[        ] [ 49%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/Payload/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.bin to device
[        ] [ 49%] Copying /Users/akash/StudioProjects/untitled/build/ios/app-delta/Runner.app.I1DDH6/Runner.app_sparse.ipa/ManifestCache.plist to device
[+1280 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[        ] [ 60%] InspectingPackage
[ +100 ms] [ 65%] PreflightingApplication
[        ] [ 67%] PatchingApplication
[ +123 ms] [ 70%] VerifyingApplication
[+1253 ms] [ 75%] CreatingContainer
[   +8 ms] [ 80%] InstallingApplication
[  +15 ms] [ 85%] PostflightingApplication
[   +4 ms] [ 90%] SandboxingApplication
[  +37 ms] [ 95%] GeneratingApplicationMap
[ +248 ms] [100%] InstallComplete
[ +452 ms] [100%] Installed package build/ios/iphoneos/Runner.app
[  +59 ms] ------ Debug phase ------
[        ] Starting debug of 00008101-00051D500110001E (D53gAP, iPhone 12, iphoneos, arm64e, 17.0, 21A5277j) a.k.a. 'AKASH’s iPhone' connected through USB...
[+2507 ms] 2023-07-16 09:33:03.238 ios-deploy[17654:136349] [ !! ] Unable to locate DeviceSupport directory with suffix 'DeveloperDiskImage.dmg'. This probably means you don't have Xcode installed, you will need to launch the app
manually and logging output will not be shown!
[   +2 ms] Script started, output file is /dev/null
[        ] Script done, output file is /dev/null
[   +1 ms] ios-deploy exited with code 0
[   +4 ms] Could not run build/ios/iphoneos/Runner.app on 00008101-00051D500110001E.
[   +2 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 11.8s)
[        ] Error launching application on AKASH’s iPhone.
[   +5 ms] "flutter run" took 71,051ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +188 ms] ensureAnalyticsSent: 180ms
[        ] Running 1 shutdown hook
[   +1 ms] Shutdown hooks complete
[        ] exiting with code 1
```
