### ISSUE TITLE
ios-deploy -c -j  does not return a correct json format

### ISSUE THREAD

**Issue by smallppgirl** [ios-control/ios-deploy#591]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

_ios-deploy -c -j_

# Expected behavior
{
  "Event" : "DeviceDetected",
  "Interface" : "USB",
  "Device" : {
    "BuildVersion" : "19H218",
    "modelSDK" : "iphoneos",
    "DeviceIdentifier" : "xxxxxxxxxx",
    "DeviceClass" : "iPhone",
    "ProductType" : "iPhone8,1",
    "DeviceName" : "“Pinky Trump”的 iPhone",
    "ProductVersion" : "15.7.2",
    "modelArch" : "arm64",
    "HardwareModel" : "N71mAP",
    "modelName" : "iPhone 6s"
  }
},{
  "Event" : "DeviceDetected",
  "Interface" : "USB",
  "Device" : {
    "BuildVersion" : "19D52",
    "modelSDK" : "iphoneos",
    "DeviceIdentifier" : "xxxxxxxxxxxx",
    "DeviceClass" : "iPhone",
    "ProductType" : "iPhone14,4",
    "DeviceName" : "xxxxx iPhone",
    "ProductVersion" : "15.3.1",
    "modelArch" : "arm64e",
    "HardwareModel" : "D16AP",
    "modelName" : "iPhone 13 Mini"
  }
}
# Actual behavior.
{
  "Event" : "DeviceDetected",
  "Interface" : "USB",
  "Device" : {
    "BuildVersion" : "19H218",
    "modelSDK" : "iphoneos",
    "DeviceIdentifier" : "xxxxxxxxxx",
    "DeviceClass" : "iPhone",
    "ProductType" : "iPhone8,1",
    "DeviceName" : "“Pinky iPhone",
    "ProductVersion" : "15.7.2",
    "modelArch" : "arm64",
    "HardwareModel" : "N71mAP",
    "modelName" : "iPhone 6s"
  }
}{ 
  "Event" : "DeviceDetected",
  "Interface" : "USB",
  "Device" : {
    "BuildVersion" : "19D52",
    "modelSDK" : "iphoneos",
    "DeviceIdentifier" : "xxxxxxxxxxxx",
    "DeviceClass" : "iPhone",
    "ProductType" : "iPhone14,4",
    "DeviceName" : "xxxxx iPhone",
    "ProductVersion" : "15.3.1",
    "modelArch" : "arm64e",
    "HardwareModel" : "D16AP",
    "modelName" : "iPhone 13 Mini"
  }
}%  

# Steps to reproduce the problem
in terminal run cmd: ios-deploy -c -j 
and check the result

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
- [ ] Software:

    System Software Overview:

      System Version: macOS 13.5 (22G74)
      Kernel Version: Darwin 22.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: C02XXXXXXXXXXXXXX
      User Name: ANDY (andy)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 hours, 14 minutes

- [ ] 2. ios-deploy -V   
1.12.2

- [ ] 3. xcodebuild -version.  
Xcode 14.3

Build version 14E222b
- [ ] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

- [ ] 5. gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

- [ ] 6. lldb --version
lldb-1403.0.17.64
Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)

**Comment by krin-san** [comment]
In Ruby (Fastlane) I have found a workaround for this issue, but would be great to have a permanent fix instead.

```ruby
output = %x{ ios-deploy -c -t 1 -W -j }

JSON.parse(output)
Traceback (most recent call last):
        6: from /usr/bin/irb:23:in `<main>'
        5: from /usr/bin/irb:23:in `load'
        4: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):7
        2: from /Users/gitlab/.gem/ruby/2.6.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
        1: from /Users/gitlab/.gem/ruby/2.6.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
JSON::ParserError (unexpected token at '{)
  "Event" : "DeviceDetected",
  ...

JSON.parse("[#{output.gsub('}{', '}, {')}]")
=> [{"Event"=>"DeviceDetected",  ...
```
